name: Infra-Deployer

on:
  workflow_call:
    inputs:
      target_env:
        type: string
        required: true
      app:
        type: string
        required: true
    secrets:
      env_vars:
        required: true

jobs:
  deploy:
    runs-on: apifornia-${{ inputs.target_env }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: App check
        run: |
          if [ -d "./docker-compose/${{ inputs.target_env }}/${{ inputs.app }}" ]; then
            Okay :)
          else
            Application does for exist for the selected env -  ${{ inputs.target_env }}
            exit 1
          fi

      - name: Generate .env file
        run: echo "${{ secrets.env_vars }}" > .env

      - name: Docker Compose Down
        run: >
          /usr/bin/docker compose
          -f ./docker-compose/${{ inputs.target_env }}/${{ inputs.app }}/docker-compose.yml
          down || true


      - name: Docker Compose up
        run: >
          /usr/bin/docker compose
          -f ./docker-compose/${{ inputs.target_env }}/${{ inputs.app }}/docker-compose.yml
          --env-file .env
          up --detach
