on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      action:
        type: string
        required: true
      app:
        type: string
        required: true

jobs:
  restarter:
    runs-on: apifornia-${{ inputs.env }}
    steps:
      - name: Restarts
        run: |
          ALL_BASE=("mongo" "kafka" "zookeeper" "postgres" "traefik" "filebeat" "ghost" "landing_proxy")
          ALL_APPS=("cat" "dog")

          if [ "${{ inputs.app }}" == 'ALL' ]; then
            for str in ${ALL_BASE[@]}; do
              docker ${{ inputs.action }} $str || true
            done
            for str in ${ALL_APPS[@]}; do
              docker ${{ inputs.action }} $str || true
            done
          fi

          if [ "${{ inputs.app }}" == 'ALL_BASE' ]; then
            for str in ${ALL_BASE[@]}; do
              docker ${{ inputs.action }} $str || true
            done
          fi

          if [ "${{ inputs.app }}" == 'ALL_APPS' ]; then
            for str in ${ALL_APPS[@]}; do
              docker ${{ inputs.action }} $str || true
            done
          fi

          if [ "${{ inputs.app }}" != 'ALL' ] && [ "${{ inputs.app }}" != 'ALL_BASE' ] && [ "${{ inputs.app }}" != 'ALL_APPS' ]; then
            docker ${{ inputs.action }} ${{ inputs.app }} || true
          fi

  # telegram_notify:
  #   if: ${{ always() }}
  #   needs: [ restarts ]
  #   uses: apifornia/github-workflows/.github/workflows/simple_telegram.yml@main
  #   with:
  #     status: "FAILURE"
  #     tg_msg: "E2E ${{ inputs.env }}"
  #   secrets:
  #     tg_bot: ${{ vars.TELEGRAM_BOT }}
  #     tg_channel: ${{ vars.TELEGRAM_CHANNEL }}
