on:
  workflow_call:
    inputs:
      test_command:
        type: string
        default: 'npm run test'
        required: false
      node_version:
        type: string
        default: '18'
        required: false

jobs:
  tests:
    name: tests
    runs-on: apifornia-builder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - run: ${{ inputs.test_command }}
