on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
    secrets:
      dev:
        required: false
      prod:
        required: false

jobs:
  test:
    runs-on: apifornia-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate .env file
        run: echo "${{ secrets.dev }}" > dev.env && echo "${{ secrets.prod }}" > prod.env

      - name: Run tests
        run: |
          npm install
          # CLEANUP
          docker container rm ${RUNNER_NAME}-cypress || true
          rm -rf /tmp/runner/work/cypress_save/ || true && mkdir -p /tmp/runner/work/cypress_save/ || true
          # RUN TESTS
          docker run \
            --name ${RUNNER_NAME}-cypress \
            --env-file	${{ inputs.env }}.env \
            -v ${LOCAL_FOLDER}/work/watcher/watcher:/e2e \
            -w /e2e \
            cypress/included:latest \
            --browser  firefox \
            --headless || true
          # POST ACTIONS
          docker logs ${RUNNER_NAME}-cypress | ansi2html > /tmp/runner/work/cypress_save/log.html
          docker logs ${RUNNER_NAME}-cypress > /tmp/runner/work/cypress_save/log.txt
          python3 getmsg.py /tmp/runner/work/cypress_save/log.txt > /tmp/runner/work/cypress_save/failing_flow.txt
          cp -r ./cypress/screenshots/  /tmp/runner/work/cypress_save/ || true
          EXIT=$(docker inspect ${RUNNER_NAME}-cypress --format='{{.State.ExitCode}}')
          if [ "$EXIT" != "0" ]; then
            exit 1
          else
            exit 0
          fi
