on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: "apifornia-builder"
        required: true
      env:
        type: string
        required: false
    secrets:
      dev:
        required: false
      prod:
        required: false

jobs:
  test:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate .env file
        run: echo "${{ secrets.dev }}" > dev.env && echo "${{ secrets.prod }}" > prod.env

      - id: tests
        name: E2E tests
        uses: apifornia/github-actions/watcher-action@main
        with:
          runs_on: apifornia-builder
          env_file: "${{ inputs.env }}.env"
