on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
    secrets:
      dev:
        required: false
      prod:
        required: false

jobs:
  test:
    runs-on: apifornia-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate .env file
        run: echo "${{ secrets.dev }}" > dev.env && echo "${{ secrets.prod }}" > prod.env

      - name: Run tests
        run: |
          npm install
          REAL_DOCKER_PATH=$( echo $GITHUB_WORKSPACE | sed s'/tmp\/runner/srv\/app\/apifornia-runners\/apifornia-builder/')
          # CLEANUP
          docker container rm cypress || true
          rm -rf  /tmp/runner/work/cypress_save/ || true && mkdir /tmp/runner/work/cypress_save/
          rm -rf /srv/app/apifornia-runners/apifornia-builder/work/cypress_save/*
          rm -rf $REAL_DOCKER_PATH/*
          # RUN TESTS
          #docker run --name cypress --env-file	${{ inputs.env }}.env -v $REAL_DOCKER_PATH:/e2e -w /e2e cypress/included:latest
          # docker run --name cypress --env-file	${{ inputs.env }}.env -v $REAL_DOCKER_PATH:/e2e -v /srv/app/apifornia-runners/apifornia-builder/work/cypress_save:/cypress -w /e2e cypress/included:latest  || true
          docker run \
            --name cypress \
            --env-file	${{ inputs.env }}.env \
            -v $REAL_DOCKER_PATH:/e2e \
            -v /srv/app/apifornia-runners/apifornia-builder/work/cypress_save:/cypress \
            -w /e2e cypress/included:latest \
            --browser  firefox \
            --headless || true
          # POST ACTIONS
          docker logs cypress | ansi2html > /tmp/runner/work/cypress_save/log.html
          cp -r ./cypress/screenshots/  /tmp/runner/work/cypress_save/ || true
          EXIT=$(docker inspect cypress --format='{{.State.ExitCode}}')
          if [ "$EXIT" != "0" ]; then
            exit 1
          else
            exit 0
          fi
