on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
    secrets:
      dev:
        required: false
      prod:
        required: false

jobs:
  test:
    runs-on: apifornia-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate .env file
        run: echo "${{ secrets.dev }}" > dev.env && echo "${{ secrets.prod }}" > prod.env

      - name: Run tests
        run: |
          npm install
          REAL_DOCKER_PATH=$( echo $GITHUB_WORKSPACE | sed s'/tmp\/runner/srv\/app\/apifornia-runners\/apifornia-builder/')
          docker container rm cypress || true
          rm -rf  /tmp/runner/work/cypress/ || true && mkdir /tmp/runner/work/cypress/
          docker run --name cypress --env-file	${{ inputs.env }}.env -v $REAL_DOCKER_PATH:/e2e -v /srv/app/apifornia-runners/apifornia-builder/work/cypres:/cypress -w /e2e cypress/included:latest  || true
          docker logs cypress | ansi2html > /tmp/runner/work/cypress/log.html
          cp -r ./cypress/screenshots/  /tmp/runner/work/cypress/
          
