on:
  workflow_call:
    secrets:
      dev:
        required: false
      prod:
        required: false

jobs:
  test:
    runs-on: apifornia-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

#      - name: Generate .env file
#        run: echo "${{ secrets.dev }}" > /file1 && echo "${{ secrets.dev }}" > /file1

      - run: REAL_DOCKER_PATH=$( echo $GITHUB_WORKSPACE | sed s'/tmp\/runner/srv\/app\/apifornia-runners\/apifornia-builder/') && docker run  -v $REAL_DOCKER_PATH:/e2e -w /e2e cypress/included:latest
