on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: "apifornia-builder"
        required: true
      env_vars:
        type: string
        required: false
      env_file:
        type: string
        default: ".env"
        required: false
      folder:
        type: string
        default: "./"
        required: false

jobs:
  test:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate .env file
        if: inputs.env_vars != ''
        run: echo "${{ inputs.env_vars }}" > "${{ inputs.env_file }}"

      - id: tests
        name: E2E tests
        uses: apifornia/github-actions/watcher-action@main
        with:
          runs_on: apifornia-builder
