on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  setup:
    runs-on: apifornia-builder
    outputs:
      CALLER_REPO_NAME: ${{ steps.setup.outputs.CALLER_REPO_NAME }}
      PR_NUMBER: ${{ steps.setup.outputs.PR_NUMBER }}
    steps:
      - id: setup
        name: Configuration setup
        run: |
            env
            echo ======================================
            REPOSITORY_NAME=(${GITHUB_REPOSITORY//\// })
            REF_NAME=(${GITHUB_REF_NAME//\// })
            echo Caller repo: ${REPOSITORY_NAME[1]}
            echo PR number: ${REF_NAME[0]}
            echo "CALLER_REPO_NAME=${REPOSITORY_NAME[1]}" >> $GITHUB_OUTPUT
            echo "PR_NUMBER=${REF_NAME[0]}" >> $GITHUB_OUTPUT

  infra:
    needs: [setup]
    runs-on: apifornia-builder
    strategy:
      matrix:
        app:
          - kafka
          - mongo
          - postgres
          - redis
    steps:
      - name: Clone infra
        uses: actions/checkout@v4
        with:
          repository: apifornia/infrastructure
          ref: main
          token: ${{ secrets.gh_token }}
      - name: Update and run ${{ matrix.app }}
        run: |
          echo app: ${{ matrix.app }}
          cd docker-compose/pr/${{ matrix.app }}
          pwd
          ls -lah
          sed -i 's/<pr-id>/pr-${{ needs.setup.outputs.PR_NUMBER }}-${{ needs.setup.outputs.CALLER_REPO_NAME }}/' docker-compose.yml
          docker compose down || true
          docker compose up -d
