on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  setup:
    runs-on: apifornia-builder
    outputs:
      CALLER_REPO_NAME: ${{ steps.setup.outputs.CALLER_REPO_NAME }}
      PR_NUMBER: ${{ steps.setup.outputs.PR_NUMBER }}
    steps:
      - id: setup
        name: Configuration setup
        run: |
            env
            echo ======================================
            REPOSITORY_NAME=(${GITHUB_REPOSITORY//\// })
            REF_NAME=(${GITHUB_REF_NAME//\// })
            echo Caller repo: ${REPOSITORY_NAME[1]}
            echo PR number: ${REF_NAME[0]}
            echo "CALLER_REPO_NAME=${REPOSITORY_NAME[1]}" >> $GITHUB_OUTPUT
            echo "PR_NUMBER=${REF_NAME[0]}" >> $GITHUB_OUTPUT

  infra:
    needs: [setup]
    runs-on: apifornia-builder
    strategy:
      matrix:
        app:
          - kafka
          - mongo
          - postgres
          - redis
    steps:
      - name: Clone infra
        uses: actions/checkout@v4
        with:
          repository: apifornia/infrastructure
          ref: main
          token: ${{ secrets.gh_token }}
      - name: Update and run ${{ matrix.app }}
        run: |
          echo app: ${{ matrix.app }}
          cd docker-compose/pr/${{ matrix.app }}
          pwd
          ls -lah
          sed -i 's/<pr-id>/pr-${{ needs.setup.outputs.PR_NUMBER }}-${{ needs.setup.outputs.CALLER_REPO_NAME }}/' docker-compose.yml
          echo Removing old containers
          docker compose down || true
          echo Starting service
          docker compose up -d

#  apps:
#    needs: [setup,infra]
#    runs-on: apifornia-builder
#    strategy:
#      matrix:
#        app:
#          - flow-editor-vue3
#          - flow-core
#          - worker-rust
#          - wizard
#    steps:
#      - name: Clone infra
#        uses: actions/checkout@v4
#        with:
#          repository: apifornia/${{ matrix.app }}
#          ref: main
#          token: ${{ secrets.gh_token }}
#      - name: Update and run ${{ matrix.app }}
#        run: |
#          echo app: ${{ matrix.app }}
#          cd docker-compose/pr/${{ matrix.app }}
#          pwd
#          ls -lah
#          sed -i 's/<pr-id>/pr-${{ needs.setup.outputs.PR_NUMBER }}-${{ needs.setup.outputs.CALLER_REPO_NAME }}/' docker-compose.yml
#          Removing old containers
#          docker compose down || true
#          Starting service
#          docker compose up -d

#  tests:
#    needs: [setup,infra,apps]
#    runs-on: apifornia-builder
#    strategy:
#      matrix:
#        app:
#          - flow-editor-vue3
#          - flow-core
#          - worker-rust
#          - wizard

#  wipe-apps:
#    needs: [setup,infra,apps,tests]
#    runs-on: $RUNS_ON
#    strategy:
#      matrix:
#        app:
#          - flow-editor-vue3
#          - flow-core
#          - worker-rust
#          - wizard
#    steps:
#      - name: Clone infra
#        uses: actions/checkout@v4
#        with:
#          repository: apifornia/${{ matrix.app }}
#          ref: main
#          token: ${{ secrets.gh_token }}
#      - name: Update and run ${{ matrix.app }}
#        run: |
#          echo app: ${{ matrix.app }}
#          cd docker-compose/pr/${{ matrix.app }}
#          pwd
#          ls -lah
#          sed -i 's/<pr-id>/pr-${{ needs.setup.outputs.PR_NUMBER }}-${{ needs.setup.outputs.CALLER_REPO_NAME }}/' docker-compose.yml
#          Removing old containers
#          docker compose down || true
#          Starting service
#          docker compose up -d

  wipe-infra:
    needs: [setup,infra]
    if: ${{ always() }}
    runs-on: apifornia-builder
    strategy:
      matrix:
        app:
          - kafka
          - mongo
          - postgres
          - redis
    steps:
      - name: Clone infra
        uses: actions/checkout@v4
        with:
          repository: apifornia/infrastructure
          ref: main
          token: ${{ secrets.gh_token }}
      - name: Cleanup ${{ matrix.app }}
        run: |
          echo app: ${{ matrix.app }}
          cd docker-compose/pr/${{ matrix.app }}
          pwd
          ls -lah
          sed -i 's/<pr-id>/pr-${{ needs.setup.outputs.PR_NUMBER }}-${{ needs.setup.outputs.CALLER_REPO_NAME }}/' docker-compose.yml
          echo Cleanup
          docker compose down || true
