on:
  workflow_call:
    inputs:
      token:
        type: string
        default: ''
        required: false


jobs:
  setup:
    runs-on: apifornia-builder
    steps:
      - id: setup
        name: Configuration setup
        run: |
            env
            split=(${GITHUB_REPOSITORY//\// })
            echo ${split[1]}
            echo "CALLER_REPO_NAME=${split[1]}" >> $GITHUB_OUTPUT
