on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: "apifornia-builder"
        required: true
      local_path:
        type: string
        required: true
      remote_path:
        type: string
        required: true
    secrets:
      host:
        required: true
      username:
        required: true
      password:
        required: true

jobs:
  test:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - id: copy
        name: Copy
        run: |
          # script
          sshpass -p "${{ secrets.password }}" ssh -p 23 -o StrictHostKeyChecking=no ${{ secrets.username }}@${{ secrets.host }} "mkdir -p  ${{ inputs.remote_path }}"
          sshpass -p "${{ secrets.password }}" scp -o StrictHostKeyChecking=no -r ${{ secrets.username }}@${{ secrets.host }}:${{ inputs.remote_path }} ${{ inputs.local_path }}
