on:
  workflow_call:
    outputs:
      CALLER_REPO_NAME:
        value: ${{ jobs.setup.outputs.CALLER_REPO_NAME }}
      DEPLOY_RUNNER:
        value: ${{ jobs.setup.outputs.DEPLOY_RUNNER }}
      EXTRA_TAG:
        value: ${{ jobs.setup.outputs.EXTRA_TAG }}

jobs:
  setup:
    runs-on: apifornia-builder
    outputs:
      CALLER_REPO_NAME: ${{ steps.setup.outputs.CALLER_REPO_NAME }}
      DEPLOY_RUNNER: ${{ steps.setup.outputs.DEPLOY_RUNNER }}
      EXTRA_TAG: ${{ steps.setup.outputs.EXTRA_TAG }}
    steps:
      - id: setup
        name: Deploy and Tag logic
        run: |
            split=(${GITHUB_REPOSITORY//\// })
            
            echo "CALLER_REPO_NAME=${split[1]}" >> $GITHUB_OUTPUT
            
            # check if this is a PR or not
            if [ ${GITHUB_EVENT_NAME} == 'pull_request' ]; then
              
              STRATEGY="PR-based"
              
              PR_N=$(echo "$GITHUB_REF_NAME" | awk -F / '{print $1}')

              EXTRA_TAG=pr-${split[1]}-${PR_N}
              echo "EXTRA_TAG=pr-${split[1]}-${PR_N}" >> $GITHUB_OUTPUT
              
              DEPLOY_RUNNER=apifornia-dev
              echo "DEPLOY_RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
              
              OK="yes"
            else
              # okay not a PR
              # TAG based deployment ?
              if [ ${GITHUB_REF_TYPE} == 'tag' ]; then
                
                STRATEGY="tag-based"

                if [ ${GITHUB_REF_NAME} == 'dev' ]; then
                  EXTRA_TAG=dev
                  echo "EXTRA_TAG=dev" >> $GITHUB_OUTPUT

                  DEPLOY_RUNNER=apifornia-dev
                  echo "DEPLOY_RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
                  
                  OK="yes"
                fi
                if [ ${GITHUB_REF_NAME} == 'prod' ]; then
                  EXTRA_TAG=dev
                  echo "EXTRA_TAG=dev" >> $GITHUB_OUTPUT
                  DEPLOY_RUNNER=apifornia-prod

                  echo "DEPLOY_RUNNER=apifornia-prod" >> $GITHUB_OUTPUT
                  OK="yes"
                fi
              fi
              
              # BRANCH based deployment ?
              if [ ${GITHUB_REF_TYPE} == 'branch' ]; then
                
                STRATEGY="branch-based"
                
                if [ ${GITHUB_REF_NAME} == 'develop' ]; then
                  EXTRA_TAG=dev
                  echo "EXTRA_TAG=dev" >> $GITHUB_OUTPUT
                  
                  DEPLOY_RUNNER=apifornia-dev
                  echo "DEPLOY_RUNNER=apifornia-dev" >> $GITHUB_OUTPUT

                  OK="yes"
                fi
                #=================================================\/
                # to delete
                #=================================================
                if [ ${GITHUB_REF_NAME} == 'pr' ]; then
                  echo "EXTRA_TAG=something-remarkable" >> $GITHUB_OUTPUT
                  echo "DEPLOY_RUNNER=apifornia-dev" >> $GITHUB_OUTPUT
                  OK="yes"
                fi
                #=================================================/\
              fi
            fi

            if [ ${OK} == 'yes' ]; then
              echo "All good"
              echo "Strategy: ${STRATEGY}"
              echo "Extra tag: ${EXTRA_TAG}"
              echo "Runner: ${DEPLOY_RUNNER}"
            else
              echo "==========================================================================================="
              echo "ERROR: Unfortunately pr/tag/branch logic failed to selected needed deploy strategy and tag"
              echo "==========================================================================================="
              exit 1
            fi
