on:
  workflow_call:
    secrets:
      tg_bot:
        required: true
      tg_channel:
        required: true

jobs:
  setup:
    runs-on: apifornia-builder
    steps:
      - id: fail
        name: baaad
        run: exit 1
      - id: send_tg
        if: always()
        name: Send Telegram message
        run: |
          TELEGRAM_MESSAGE="$GITHUB_WORKFLOW > $GITHUB_JOB > ${{ job.status }}"
          curl -s -X POST -d chat_id="${{ secrets.tg_channel }}" -d text="$TELEGRAM_MESSAGE" -d parse_mode=HTML -d disable_web_page_preview=true https://api.telegram.org/bot${{ secrets.tg_bot }}/sendMessage || true
