on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: 'apifornia-builder'
        required: false
      status:
        type: string
        default: ''
        required: false
      tg_msg:
        type: string
        default: ''
        required: false
    secrets:
      tg_bot:
        required: true
      tg_channel:
        required: true

jobs:
  telegram:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - id: sendMessage
        name: Send Telegram message OK
        run: |
          if [ "${{ inputs.tg_msg }}" == '' ]; then
            TELEGRAM_MESSAGE="<a href='https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/'>$GITHUB_WORKFLOW > $GITHUB_JOB > <b>${{ inputs.status }}</b></a>"
          else
            TELEGRAM_MESSAGE="<a href='https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/'>${{ inputs.tg_msg }} > <b>${{ inputs.status }}</b></a>"
          fi
          curl -s -X POST -d chat_id="${{ secrets.tg_channel }}" -d text="$TELEGRAM_MESSAGE" -d parse_mode=HTML -d disable_web_page_preview=true https://api.telegram.org/bot${{ secrets.tg_bot }}/sendMessage || true
