on:
  workflow_call:
    inputs:
      tg_bot:
        type: string
        default: ''
        required: true
      tg_channel:
        type: string
        default: ''
        required: true

jobs:
  setup:
    runs-on: apifornia-builder
    steps:
      - id: send_tg
        name: Send Telegram message
        run: |
          TELEGRAM_MESSAGE="${{ env.GITHUB_WORKFLOW }} > ${{ env.GITHUB_WORKFLOW }} > ${{ job.status }}"
          curl -s -X POST -d chat_id="${{ inputs.tg_channel }}" -d text="$TELEGRAM_MESSAGE" -d parse_mode=HTML -d disable_web_page_preview=true https://api.telegram.org/bot${{ inputs.tg_bot }}/sendMessage || true
