on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: 'apifornia-builder'
        required: false
      file:
        type: string
        default: ''
        required: true
    secrets:
      tg_bot:
        required: true
      tg_channel:
        required: true

jobs:
  telegram:
    runs-on: ${{ inputs.runs_on }}
    steps:
      - id: sendDocument
        name: Send Telegram File
        run: |
          curl -X POST -F document=@"${{ inputs.file }}" https://api.telegram.org/bot${{ secrets.tg_bot }}/sendDocument?chat_id=${{ secrets.tg_channel }} || true
