on:
  workflow_call:

jobs:
  test:
    runs-on: apifornia-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: ENV
        run: env
      - name: test vars
        run: echo "${{ vars.TELEGRAM_BOT }}"
