on:
  workflow_call:

jobs:
  tests:
    name: tests
    runs-on: apifornia-builder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Setup
        run: |
          pip install poetry==1.8.3
          poetry install
      - name: Run ruff lint
        run: |
          poetry run ruff .
      - name: Run ruff formatting check
        run: |
          poetry run ruff format --diff .
      - name: Run tests
        run: |
          export $(cat .env.public | xargs)
          poetry run pytest
