on:
  workflow_call:

jobs:
  tests:
    name: tests
    runs-on: apifornia-builder
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          pytest tests
